version: 2
updates:
  - package-ecosystem: npm
    directory: /
    commit-message:
      prefix: build
      prefix-development: build
    schedule:
      interval: weekly
    groups:
      npm-dependencies:
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    commit-message:
      prefix: ci
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
